PushWeb/Models/TipViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PushWeb.Models
{
    public class TipViewModel
    {
        public int TipID { get; set; }
        public string TipText { get; set; }

        public TipViewModel(int tipid, string tiptext)
        {
            this.TipID = tipid;
            this.TipText = tiptext;
        }

        public TipViewModel()
        {
        }
    }
}

PushWeb/Controllers/TipController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using PushBAL;
using PushDAL;
using PushWeb.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PushWeb.Controllers
{
    public class TipController : Controller
    {      
        TipContainer tipContainer = new TipContainer();

        [HttpGet]
        public IActionResult Index()
        {
            if (!HttpContext.Session.GetInt32("userid").HasValue)
            {
                return RedirectToRoute(new { Controller = "Login", Action = "Index" });
            }
            List<Tip> tips = tipContainer.GetAllTip();
            TipListViewModel tipListViewModels = new TipListViewModel();

           

            foreach (Tip item in tips)
            {
                tipListViewModels.lists.Add(new TipViewModel(item.TipID, item.tip));
            }
            return View(tipListViewModels);
        }

        [HttpGet]
        public IActionResult AddTip()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AddTip(TipViewModel ntvm)
        {
            if (ModelState.IsValid)
            {
                Tip tip = new Tip(ntvm.TipText);

                tip.AddTip(new TipDAL());
                return RedirectToAction("Index");
                
            }
            return View("Register");
        }

        [HttpGet]
        public IActionResult EditTip(int tipID)
        {
            int? userID = HttpContext.Session.GetInt32("userid");

            if (!userID.HasValue)
            {
                return RedirectToRoute(new { Controller = "Login", Action = "Index" });
            }
            else
            {
                TipViewModel tvm = new TipViewModel();
                Tip tip = tipContainer.GetSelectedTip(tipID);
               
                tvm.TipID = tip.TipID;
                tvm.TipText = tip.tip;
                return View(tvm);
            }
        }

        [HttpPost]
        public IActionResult EditTip(TipViewModel tvm)
        {
            int? userID = HttpContext.Session.GetInt32("userid");

            if (!userID.HasValue)
            {
                return RedirectToRoute(new { Controller = "Login", Action = "Index" });
            }
            else
            {
                Tip tip = new Tip(
                    tvm.TipID,
                    tvm.TipText);
               

                tipContainer.EditTip(tip);

                return RedirectToAction("Index");
            }
        }

        [HttpGet]
        public IActionResult DeleteTip(int tipID)
        {
            int? userID = HttpContext.Session.GetInt32("userid");

            if (!userID.HasValue)
            {
                return RedirectToRoute(new { Controller = "Login", Action = "Index" });
            }
            else
            {
                Tip tip = new Tip(tipID);
                

                tipContainer.DeleteTip(tip);

                return RedirectToAction("Index");
            }
        }
    }
}

PushWeb/Views/Tips/AddTip.cshtml
@model PushWeb.Models.TipViewModel
@{
    ViewData["Title"] = "Add new tip";
}
@{
    Layout = null;
}
<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
<link rel="stylesheet" href="~/css/site.css" />

<div class="container" style="margin-top:30px">
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading"><h3 class="panel-title"><strong>Add new tip </strong></h3></div>
            <div class="panel-body">
                <form asp-action="AddTip" method="post">                   
                    <div class="form-group">
                        <label asp-for="TipText" class="control-label"></label>
                        <input asp-for="TipText" class="form-control" id="exampleInputUsername" placeholder="Enter Name">
                        <span asp-validation-for="TipText" class="text-danger"></span>
                    </div>                    
                    <div class="form-group">
                        <input type="submit" class="btn btn-primary" value="Add tip" />
                        <a asp-controller="Tip" asp-action="Admin" class="btn btn-primary">Cancel</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

PushWeb/Views/Tips/Admin.cshtml
@model TipListViewModel
@{
    ViewData["Title"] = "Tips admin panel";
}

<div class="container">
    <div class="row">
        <form asp-action="Admin" method="post">
            <div class="col-xl-8" style="margin-top:30px">
                <div class="panel panel-default">
                    <div class="panel-heading">

                        <div class="text-end">
                            <a class="btn btn-primary" asp-controller="Tips" asp-action="AddTip">Add <i class="fas fa-plus"></i></a>
                        </div>
                        <h3 class="panel-title">
                            <strong>Tips overview</strong>
                        </h3>
                    </div>
                    <div class="panel-body">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Tip id</th>
                                    <th>Text</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var tip in Model.lists)
                                {
                                    <tr>
                                        <td>
                                            @Html.ValueFor(model => tip.TipID)
                                        </td>
                                        <td>
                                            @Html.ValueFor(model => tip.TipText)
                                        </td>
                                        <td>
                                            <a class="btn btn-warning" asp-controller="Tip" asp-action="EditTip" asp-route-weightId="@tip.TipID"><i class="far fa-edit"></i></a>
                                            <a class="btn btn-danger" asp-controller="Tip" asp-action="DeleteTip" asp-route-weightId="@tip.TipID"><i class="far fa-trash-alt"></i></a>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

PushWeb/Views/Tips/EditTip.cshtml
@model PushWeb.Models.TipViewModel
@{
    ViewData["Title"] = "Edit tip";
}
@{
    Layout = null;
}
<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
<link rel="stylesheet" href="~/css/site.css" />

<div class="container" style="margin-top:30px">
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading"><h3 class="panel-title"><strong>Edit tip </strong></h3></div>
            <div class="panel-body">
                <form asp-action="EditTip" method="post">
                    <div class="form-group">
                        <label asp-for="TipText" class="control-label"></label>
                        <input asp-for="TipText" class="form-control" id="exampleInputUsername" placeholder="Enter text">
                        <span asp-validation-for="TipText" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input type="submit" class="btn btn-primary" value="Edit tip" />
                        <a asp-controller="Tip" asp-action="Admin" class="btn btn-primary">Cancel</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>