PushWeb/Models/RecipeBookViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PushWeb.Models
{
    public class RecipeBookViewModel
    {
        public int RecipeBookID { get; set; }
        public string RecipeType { get; set; }

        public RecipeBookViewModel()
        {

        }

        public RecipeBookViewModel(int recipebookID)
        {
            this.RecipeBookID = recipebookID;          
        }

        public RecipeBookViewModel(int recipebookID, string recipetype)
        {
            this.RecipeBookID = recipebookID;
            this.RecipeType = recipetype;
        }
    }
}

PushWeb/Controllers/RecipeBookController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using PushBAL;
using PushDAL;
using PushWeb.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PushWeb.Controllers
{
    public class RecipeBookController : Controller
    {
        RecipeBookContainer recipeBookContainer = new RecipeBookContainer(new RecipeBookDAL());

        [HttpGet]
        public IActionResult Index()
        {
            if (!HttpContext.Session.GetInt32("userid").HasValue)
            {
                return RedirectToRoute(new { Controller = "Login", Action = "Index" });
            }           
            else
            {
                List<RecipeBook> recipeBooks = recipeBookContainer.GetAllTypes();
                RecipeBookListViewModel recipeListViewModel = new RecipeBookListViewModel();
                
                foreach (RecipeBook item in recipeBooks)
                {
                    recipeListViewModel.lists.Add(new RecipeBookViewModel(item.RecipeBookID, item.RecipeType));                  
                }
                return View(recipeListViewModel);
            }
        }
    }
}

PushWeb/Controllers/RecipeController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using PushBAL;
using PushDAL;
using PushWeb.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PushWeb.Controllers
{
    public class RecipeController : Controller
    {
        RecipeContainer recipeContainer = new RecipeContainer(new RecipeDAL());

        [HttpGet]
        public IActionResult List(int recipebookID)
        {
            if (!HttpContext.Session.GetInt32("userid").HasValue)
            {
                return RedirectToRoute(new { Controller = "Login", Action = "Index" });
            }
            else
            {
                List<Recipe> recipes = recipeContainer.GetAllRecipe(recipebookID);
                RecipeListViewModel recipeListViewModel = new RecipeListViewModel();

                foreach (Recipe item in recipes)
                {
                    recipeListViewModel.lists.Add(new RecipeViewModel(item.RecipeID, item.Name, item.Description, item.RecipeBookID));
                }
                return View(recipeListViewModel);
            }
        }

        [HttpGet]
        public IActionResult Details(int recipeID)
        {
            if (!HttpContext.Session.GetInt32("userid").HasValue)
            {
                return RedirectToRoute(new { Controller = "Login", Action = "Index" });
            }
            else
            {
                Recipe recipe = new Recipe(recipeID);
                recipe= recipe.GetSelectedRecipe(new RecipeDAL(),recipeID);
                RecipeViewModel rvm = new RecipeViewModel(recipe);

                return View(rvm);                
            }
        }
    }
}

PushWeb/Views/RecipeBook/Index.cshtml
@model PushWeb.Models.RecipeBookListViewModel
@{
    ViewData["Title"] = "Recipebook";
}

<h1>Recipebook</h1>
<div class="container">
    <div class="row align-items-center d-flex justify-content-center">
        @foreach (var book in Model.lists)
         {
            <div class="col-md-3">
                <div class="card" style="height: 12rem">
                    <div class="card-body" style=" background-color:#A7CDD5;">
                        @Html.HiddenFor(model => book.RecipeBookID)
                        <div class="row align-items-center d-flex justify-content-center" style="font-size:30px">
                            @Html.DisplayFor(model => book.RecipeType)
                        </div>                      
                    </div>
                    <div class="footer" style="text-align:center">
                        <a asp-controller="Recipe" asp-action="List" , asp-route-recipebookId="@book.RecipeBookID" class="btn btn-success m-1">Select</a>
                    </div>
                </div>
           </div>
         }
    </div>
</div>