PushWeb/Models/MotivationViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PushWeb.Models
{
    public class MotivationViewModel
    {
        public int MotivationID { get; set; }
        public string Text { get; set; }
        public bool Positive { get; set; }

        public MotivationViewModel()
        {

        }

        public MotivationViewModel(int motivationID)
        {
            this.MotivationID = motivationID;         
        }

        public MotivationViewModel(int motivationID, string text, bool positive)
        {
            this.MotivationID = motivationID;
            this.Text = text;
            this.Positive = positive;
        }
    }
}

PushWeb/Controllers/MotivationController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PushWeb.Controllers
{
    public class MotivationController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

PushWeb/Views/Motivation/AddMotivation.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

PushWeb/Views/Motivation/Admin.cshtml
@model MotivationListViewModel
@{
    ViewData["Title"] = "Motivations admin panel";
}

<div class="container">
    <div class="row">
        <form asp-action="Admin" method="post">
            <div class="col-xl-8" style="margin-top:30px">
                <div class="panel panel-default">
                    <div class="panel-heading">

                        <div class="text-end">
                            <a class="btn btn-primary" asp-controller="Motivation" asp-action="AddMotivation">Add <i class="fas fa-plus"></i></a>
                        </div>
                        <h3 class="panel-title">
                            <strong>Tips overview</strong>
                        </h3>
                    </div>
                    <div class="panel-body">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Motivation id</th>
                                    <th>Text</th>
                                    <th>Positive</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var motivation in Model.lists)
                                {
                                <tr>
                                    <td>
                                        @Html.ValueFor(model => motivation.MotivationID)
                                    </td>
                                    <td>
                                        @Html.ValueFor(model => motivation.Text)
                                    </td>
                                    <td>
                                        @Html.ValueFor(model => motivation.Positive)
                                    </td>
                                    <td>
                                        <a class="btn btn-warning" asp-controller="Motivation" asp-action="EditMotivation" asp-route-weightId="@motivation.MotivationID"><i class="far fa-edit"></i></a>
                                        <a class="btn btn-danger" asp-controller="Motivation" asp-action="DeleteMotivation" asp-route-weightId="@motivation.MotivationID"><i class="far fa-trash-alt"></i></a>
                                    </td>
                                </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

PushWeb/Views/Motivation/EditMotivation.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}